color:
  brandColors:
    - '#010101'
    - '#003E49'
    - '#045B6D'
    - '#172830'
    - '#2AB3F1'
  brandStrength: 0.9586662820074707
  lightness: 0.7328828985337168
  saturation: 0.08361940132454038
  rhythmicContrast: 0.8371392739936709
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: coalition-testing
layout_spectrum: 0.1803131466731429
typography_spectrum: 0.08014019043184817
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff569fc6-bba6-4c9f-bcea-7c3716ad5ca5.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff569fc6-bba6-4c9f-bcea-7c3716ad5ca5.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Coalition testing
description: Under Construction
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f32096e6-71f5-4676-989d-b9112c53c1a3.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/86d30a22-c1dc-4d28-a8b8-0ee6459c604c.png
content_rating:
  adult: false
author:
  email: mr.lyder@hotmail.com
  url: 'https://www.pushcoalition.nl/'
  name: Kim A.L Evensen
